version: '3.7'
services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    image: tl_client
    container_name: tl_client
    restart: always
    ports:
      - '9100:80'
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '1'
networks:
  default:
    external:
      name: tl_net
