version: '3.7'
services:
  ref-books-db:
    image: 'postgres:10-alpine'
    container_name: tl_ref_books_db
    restart: always
    ports:
      - '9191:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    env_file: ../run/db/db.env
networks:
  default:
    external:
      name: tl_net
volumes:
  db:
