version: '3.7'
services:
  api:
    build:
      context: ../server
      dockerfile: src/Services/ReferenceBook/ReferenceBook.Api/Dockerfile
    image: tl_ref_books_api
    container_name: tl_ref_books_api
    restart: always
    ports:
      - '9502:80'
    volumes:
      - '../run/configuration:/app/configuration'
      - '../run/keys:/app/keys'
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '1'
networks:
  default:
    external:
      name: tl_net
