//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9148
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace TaxLegal.Cbc.Report.Application.Schemas.V200.Models.Xml
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oecd:ties:cbc:v2")]
    [XmlRoot(Namespace="urn:oecd:ties:cbc:v2", IsNullable=false)]
    public class CBC_OECD {

        private MessageSpec_Type messageSpecField;

        private CbcBody_Type[] cbcBodyField;

        private string versionField;

        /// <remarks/>
        public MessageSpec_Type MessageSpec {
            get {
                return this.messageSpecField;
            }
            set {
                this.messageSpecField = value;
            }
        }

        /// <remarks/>
        [XmlElement("CbcBody")]
        public CbcBody_Type[] CbcBody {
            get {
                return this.cbcBodyField;
            }
            set {
                this.cbcBodyField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class MessageSpec_Type {

        private string sendingEntityINField;

        private CountryCode_Type transmittingCountryField;

        private CountryCode_Type[] receivingCountryField;

        private MessageType_EnumType messageTypeField;

        private LanguageCode_Type languageField;

        private bool languageFieldSpecified;

        private string warningField;

        private string contactField;

        private string messageRefIdField;

        private CbcMessageTypeIndic_EnumType messageTypeIndicField;

        private string[] corrMessageRefIdField;

        private System.DateTime reportingPeriodField;

        private System.DateTime timestampField;

        /// <remarks/>
        public string SendingEntityIN {
            get {
                return this.sendingEntityINField;
            }
            set {
                this.sendingEntityINField = value;
            }
        }

        /// <remarks/>
        public CountryCode_Type TransmittingCountry {
            get {
                return this.transmittingCountryField;
            }
            set {
                this.transmittingCountryField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ReceivingCountry")]
        public CountryCode_Type[] ReceivingCountry {
            get {
                return this.receivingCountryField;
            }
            set {
                this.receivingCountryField = value;
            }
        }

        /// <remarks/>
        public MessageType_EnumType MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
            }
        }

        /// <remarks/>
        public LanguageCode_Type Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool LanguageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
            }
        }

        /// <remarks/>
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }

        /// <remarks/>
        public string MessageRefId {
            get {
                return this.messageRefIdField;
            }
            set {
                this.messageRefIdField = value;
            }
        }

        /// <remarks/>
        public CbcMessageTypeIndic_EnumType MessageTypeIndic {
            get {
                return this.messageTypeIndicField;
            }
            set {
                this.messageTypeIndicField = value;
            }
        }

        /// <remarks/>
        [XmlElement("CorrMessageRefId")]
        public string[] CorrMessageRefId {
            get {
                return this.corrMessageRefIdField;
            }
            set {
                this.corrMessageRefIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType="date")]
        public System.DateTime ReportingPeriod {
            get {
                return this.reportingPeriodField;
            }
            set {
                this.reportingPeriodField = value;
            }
        }

        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:isocbctypes:v1")]
    public enum CountryCode_Type {

        /// <remarks/>
        AF,

        /// <remarks/>
        AX,

        /// <remarks/>
        AL,

        /// <remarks/>
        DZ,

        /// <remarks/>
        AS,

        /// <remarks/>
        AD,

        /// <remarks/>
        AO,

        /// <remarks/>
        AI,

        /// <remarks/>
        AQ,

        /// <remarks/>
        AG,

        /// <remarks/>
        AR,

        /// <remarks/>
        AM,

        /// <remarks/>
        AW,

        /// <remarks/>
        AU,

        /// <remarks/>
        AT,

        /// <remarks/>
        AZ,

        /// <remarks/>
        BS,

        /// <remarks/>
        BH,

        /// <remarks/>
        BD,

        /// <remarks/>
        BB,

        /// <remarks/>
        BY,

        /// <remarks/>
        BE,

        /// <remarks/>
        BZ,

        /// <remarks/>
        BJ,

        /// <remarks/>
        BM,

        /// <remarks/>
        BT,

        /// <remarks/>
        BO,

        /// <remarks/>
        BQ,

        /// <remarks/>
        BA,

        /// <remarks/>
        BW,

        /// <remarks/>
        BV,

        /// <remarks/>
        BR,

        /// <remarks/>
        IO,

        /// <remarks/>
        BN,

        /// <remarks/>
        BG,

        /// <remarks/>
        BF,

        /// <remarks/>
        BI,

        /// <remarks/>
        KH,

        /// <remarks/>
        CM,

        /// <remarks/>
        CA,

        /// <remarks/>
        CV,

        /// <remarks/>
        KY,

        /// <remarks/>
        CF,

        /// <remarks/>
        TD,

        /// <remarks/>
        CL,

        /// <remarks/>
        CN,

        /// <remarks/>
        CX,

        /// <remarks/>
        CC,

        /// <remarks/>
        CO,

        /// <remarks/>
        KM,

        /// <remarks/>
        CG,

        /// <remarks/>
        CD,

        /// <remarks/>
        CK,

        /// <remarks/>
        CR,

        /// <remarks/>
        CI,

        /// <remarks/>
        HR,

        /// <remarks/>
        CU,

        /// <remarks/>
        CW,

        /// <remarks/>
        CY,

        /// <remarks/>
        CZ,

        /// <remarks/>
        DK,

        /// <remarks/>
        DJ,

        /// <remarks/>
        DM,

        /// <remarks/>
        DO,

        /// <remarks/>
        EC,

        /// <remarks/>
        EG,

        /// <remarks/>
        SV,

        /// <remarks/>
        GQ,

        /// <remarks/>
        ER,

        /// <remarks/>
        EE,

        /// <remarks/>
        ET,

        /// <remarks/>
        FK,

        /// <remarks/>
        FO,

        /// <remarks/>
        FJ,

        /// <remarks/>
        FI,

        /// <remarks/>
        FR,

        /// <remarks/>
        GF,

        /// <remarks/>
        PF,

        /// <remarks/>
        TF,

        /// <remarks/>
        GA,

        /// <remarks/>
        GM,

        /// <remarks/>
        GE,

        /// <remarks/>
        DE,

        /// <remarks/>
        GH,

        /// <remarks/>
        GI,

        /// <remarks/>
        GR,

        /// <remarks/>
        GL,

        /// <remarks/>
        GD,

        /// <remarks/>
        GP,

        /// <remarks/>
        GU,

        /// <remarks/>
        GT,

        /// <remarks/>
        GG,

        /// <remarks/>
        GN,

        /// <remarks/>
        GW,

        /// <remarks/>
        GY,

        /// <remarks/>
        HT,

        /// <remarks/>
        HM,

        /// <remarks/>
        VA,

        /// <remarks/>
        HN,

        /// <remarks/>
        HK,

        /// <remarks/>
        HU,

        /// <remarks/>
        IS,

        /// <remarks/>
        IN,

        /// <remarks/>
        ID,

        /// <remarks/>
        IR,

        /// <remarks/>
        IQ,

        /// <remarks/>
        IE,

        /// <remarks/>
        IM,

        /// <remarks/>
        IL,

        /// <remarks/>
        IT,

        /// <remarks/>
        JM,

        /// <remarks/>
        JP,

        /// <remarks/>
        JE,

        /// <remarks/>
        JO,

        /// <remarks/>
        KZ,

        /// <remarks/>
        KE,

        /// <remarks/>
        KI,

        /// <remarks/>
        KP,

        /// <remarks/>
        KR,

        /// <remarks/>
        KW,

        /// <remarks/>
        KG,

        /// <remarks/>
        LA,

        /// <remarks/>
        LV,

        /// <remarks/>
        LB,

        /// <remarks/>
        LS,

        /// <remarks/>
        LR,

        /// <remarks/>
        LY,

        /// <remarks/>
        LI,

        /// <remarks/>
        LT,

        /// <remarks/>
        LU,

        /// <remarks/>
        MO,

        /// <remarks/>
        MK,

        /// <remarks/>
        MG,

        /// <remarks/>
        MW,

        /// <remarks/>
        MY,

        /// <remarks/>
        MV,

        /// <remarks/>
        ML,

        /// <remarks/>
        MT,

        /// <remarks/>
        MH,

        /// <remarks/>
        MQ,

        /// <remarks/>
        MR,

        /// <remarks/>
        MU,

        /// <remarks/>
        YT,

        /// <remarks/>
        MX,

        /// <remarks/>
        FM,

        /// <remarks/>
        MD,

        /// <remarks/>
        MC,

        /// <remarks/>
        MN,

        /// <remarks/>
        ME,

        /// <remarks/>
        MS,

        /// <remarks/>
        MA,

        /// <remarks/>
        MZ,

        /// <remarks/>
        MM,

        /// <remarks/>
        NA,

        /// <remarks/>
        NR,

        /// <remarks/>
        NP,

        /// <remarks/>
        NL,

        /// <remarks/>
        NC,

        /// <remarks/>
        NZ,

        /// <remarks/>
        NI,

        /// <remarks/>
        NE,

        /// <remarks/>
        NG,

        /// <remarks/>
        NU,

        /// <remarks/>
        NF,

        /// <remarks/>
        MP,

        /// <remarks/>
        NO,

        /// <remarks/>
        OM,

        /// <remarks/>
        PK,

        /// <remarks/>
        PW,

        /// <remarks/>
        PS,

        /// <remarks/>
        PA,

        /// <remarks/>
        PG,

        /// <remarks/>
        PY,

        /// <remarks/>
        PE,

        /// <remarks/>
        PH,

        /// <remarks/>
        PN,

        /// <remarks/>
        PL,

        /// <remarks/>
        PT,

        /// <remarks/>
        PR,

        /// <remarks/>
        QA,

        /// <remarks/>
        RE,

        /// <remarks/>
        RO,

        /// <remarks/>
        RU,

        /// <remarks/>
        RW,

        /// <remarks/>
        BL,

        /// <remarks/>
        SH,

        /// <remarks/>
        KN,

        /// <remarks/>
        LC,

        /// <remarks/>
        MF,

        /// <remarks/>
        PM,

        /// <remarks/>
        VC,

        /// <remarks/>
        WS,

        /// <remarks/>
        SM,

        /// <remarks/>
        ST,

        /// <remarks/>
        SA,

        /// <remarks/>
        SN,

        /// <remarks/>
        RS,

        /// <remarks/>
        SC,

        /// <remarks/>
        SL,

        /// <remarks/>
        SG,

        /// <remarks/>
        SX,

        /// <remarks/>
        SK,

        /// <remarks/>
        SI,

        /// <remarks/>
        SB,

        /// <remarks/>
        SO,

        /// <remarks/>
        ZA,

        /// <remarks/>
        GS,

        /// <remarks/>
        SS,

        /// <remarks/>
        ES,

        /// <remarks/>
        LK,

        /// <remarks/>
        SD,

        /// <remarks/>
        SR,

        /// <remarks/>
        SJ,

        /// <remarks/>
        SZ,

        /// <remarks/>
        SE,

        /// <remarks/>
        CH,

        /// <remarks/>
        SY,

        /// <remarks/>
        TW,

        /// <remarks/>
        TJ,

        /// <remarks/>
        TZ,

        /// <remarks/>
        TH,

        /// <remarks/>
        TL,

        /// <remarks/>
        TG,

        /// <remarks/>
        TK,

        /// <remarks/>
        TO,

        /// <remarks/>
        TT,

        /// <remarks/>
        TN,

        /// <remarks/>
        TR,

        /// <remarks/>
        TM,

        /// <remarks/>
        TC,

        /// <remarks/>
        TV,

        /// <remarks/>
        UG,

        /// <remarks/>
        UA,

        /// <remarks/>
        AE,

        /// <remarks/>
        GB,

        /// <remarks/>
        US,

        /// <remarks/>
        UM,

        /// <remarks/>
        UY,

        /// <remarks/>
        UZ,

        /// <remarks/>
        VU,

        /// <remarks/>
        VE,

        /// <remarks/>
        VN,

        /// <remarks/>
        VG,

        /// <remarks/>
        VI,

        /// <remarks/>
        WF,

        /// <remarks/>
        EH,

        /// <remarks/>
        YE,

        /// <remarks/>
        ZM,

        /// <remarks/>
        ZW,

        /// <remarks/>
        XK,

        /// <remarks/>
        X5,

        /// <remarks/>
        XX,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public enum MessageType_EnumType {

        /// <remarks/>
        CBC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:isocbctypes:v1")]
    public enum LanguageCode_Type {

        /// <remarks/>
        AA,

        /// <remarks/>
        AB,

        /// <remarks/>
        AF,

        /// <remarks/>
        AK,

        /// <remarks/>
        SQ,

        /// <remarks/>
        AM,

        /// <remarks/>
        AR,

        /// <remarks/>
        AN,

        /// <remarks/>
        HY,

        /// <remarks/>
        AS,

        /// <remarks/>
        AV,

        /// <remarks/>
        AE,

        /// <remarks/>
        AY,

        /// <remarks/>
        AZ,

        /// <remarks/>
        BA,

        /// <remarks/>
        BM,

        /// <remarks/>
        EU,

        /// <remarks/>
        BE,

        /// <remarks/>
        BN,

        /// <remarks/>
        BH,

        /// <remarks/>
        BI,

        /// <remarks/>
        BS,

        /// <remarks/>
        BR,

        /// <remarks/>
        BG,

        /// <remarks/>
        MY,

        /// <remarks/>
        CA,

        /// <remarks/>
        CH,

        /// <remarks/>
        CE,

        /// <remarks/>
        ZH,

        /// <remarks/>
        CU,

        /// <remarks/>
        CV,

        /// <remarks/>
        KW,

        /// <remarks/>
        CO,

        /// <remarks/>
        CR,

        /// <remarks/>
        CS,

        /// <remarks/>
        DA,

        /// <remarks/>
        DV,

        /// <remarks/>
        NL,

        /// <remarks/>
        DZ,

        /// <remarks/>
        EN,

        /// <remarks/>
        EO,

        /// <remarks/>
        ET,

        /// <remarks/>
        EE,

        /// <remarks/>
        FO,

        /// <remarks/>
        FJ,

        /// <remarks/>
        FI,

        /// <remarks/>
        FR,

        /// <remarks/>
        FY,

        /// <remarks/>
        FF,

        /// <remarks/>
        KA,

        /// <remarks/>
        DE,

        /// <remarks/>
        GD,

        /// <remarks/>
        GA,

        /// <remarks/>
        GL,

        /// <remarks/>
        GV,

        /// <remarks/>
        EL,

        /// <remarks/>
        GN,

        /// <remarks/>
        GU,

        /// <remarks/>
        HT,

        /// <remarks/>
        HA,

        /// <remarks/>
        HE,

        /// <remarks/>
        HZ,

        /// <remarks/>
        HI,

        /// <remarks/>
        HO,

        /// <remarks/>
        HR,

        /// <remarks/>
        HU,

        /// <remarks/>
        IG,

        /// <remarks/>
        IS,

        /// <remarks/>
        IO,

        /// <remarks/>
        II,

        /// <remarks/>
        IU,

        /// <remarks/>
        IE,

        /// <remarks/>
        IA,

        /// <remarks/>
        ID,

        /// <remarks/>
        IK,

        /// <remarks/>
        IT,

        /// <remarks/>
        JV,

        /// <remarks/>
        JA,

        /// <remarks/>
        KL,

        /// <remarks/>
        KN,

        /// <remarks/>
        KS,

        /// <remarks/>
        KR,

        /// <remarks/>
        KK,

        /// <remarks/>
        KM,

        /// <remarks/>
        KI,

        /// <remarks/>
        RW,

        /// <remarks/>
        KY,

        /// <remarks/>
        KV,

        /// <remarks/>
        KG,

        /// <remarks/>
        KO,

        /// <remarks/>
        KJ,

        /// <remarks/>
        KU,

        /// <remarks/>
        LO,

        /// <remarks/>
        LA,

        /// <remarks/>
        LV,

        /// <remarks/>
        LI,

        /// <remarks/>
        LN,

        /// <remarks/>
        LT,

        /// <remarks/>
        LB,

        /// <remarks/>
        LU,

        /// <remarks/>
        LG,

        /// <remarks/>
        MK,

        /// <remarks/>
        MH,

        /// <remarks/>
        ML,

        /// <remarks/>
        MI,

        /// <remarks/>
        MR,

        /// <remarks/>
        MS,

        /// <remarks/>
        MG,

        /// <remarks/>
        MT,

        /// <remarks/>
        MN,

        /// <remarks/>
        NA,

        /// <remarks/>
        NV,

        /// <remarks/>
        NR,

        /// <remarks/>
        ND,

        /// <remarks/>
        NG,

        /// <remarks/>
        NE,

        /// <remarks/>
        NN,

        /// <remarks/>
        NB,

        /// <remarks/>
        NO,

        /// <remarks/>
        NY,

        /// <remarks/>
        OC,

        /// <remarks/>
        OJ,

        /// <remarks/>
        OR,

        /// <remarks/>
        OM,

        /// <remarks/>
        OS,

        /// <remarks/>
        PA,

        /// <remarks/>
        FA,

        /// <remarks/>
        PI,

        /// <remarks/>
        PL,

        /// <remarks/>
        PT,

        /// <remarks/>
        PS,

        /// <remarks/>
        QU,

        /// <remarks/>
        RM,

        /// <remarks/>
        RO,

        /// <remarks/>
        RN,

        /// <remarks/>
        RU,

        /// <remarks/>
        SG,

        /// <remarks/>
        SA,

        /// <remarks/>
        SI,

        /// <remarks/>
        SK,

        /// <remarks/>
        SL,

        /// <remarks/>
        SE,

        /// <remarks/>
        SM,

        /// <remarks/>
        SN,

        /// <remarks/>
        SD,

        /// <remarks/>
        SO,

        /// <remarks/>
        ST,

        /// <remarks/>
        ES,

        /// <remarks/>
        SC,

        /// <remarks/>
        SR,

        /// <remarks/>
        SS,

        /// <remarks/>
        SU,

        /// <remarks/>
        SW,

        /// <remarks/>
        SV,

        /// <remarks/>
        TY,

        /// <remarks/>
        TA,

        /// <remarks/>
        TT,

        /// <remarks/>
        TE,

        /// <remarks/>
        TG,

        /// <remarks/>
        TL,

        /// <remarks/>
        TH,

        /// <remarks/>
        BO,

        /// <remarks/>
        TI,

        /// <remarks/>
        TO,

        /// <remarks/>
        TN,

        /// <remarks/>
        TS,

        /// <remarks/>
        TK,

        /// <remarks/>
        TR,

        /// <remarks/>
        TW,

        /// <remarks/>
        UG,

        /// <remarks/>
        UK,

        /// <remarks/>
        UR,

        /// <remarks/>
        UZ,

        /// <remarks/>
        VE,

        /// <remarks/>
        VI,

        /// <remarks/>
        VO,

        /// <remarks/>
        CY,

        /// <remarks/>
        WA,

        /// <remarks/>
        WO,

        /// <remarks/>
        XH,

        /// <remarks/>
        YI,

        /// <remarks/>
        YO,

        /// <remarks/>
        ZA,

        /// <remarks/>
        ZU,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public enum CbcMessageTypeIndic_EnumType {

        /// <remarks/>
        CBC401,

        /// <remarks/>
        CBC402,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbcstf:v5")]
    public partial class StringMin1Max4000WithLang_Type {

        private LanguageCode_Type languageField;

        private bool languageFieldSpecified;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public LanguageCode_Type language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool languageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class CorrectableAdditionalInfo_Type {

        private DocSpec_Type docSpecField;

        private StringMin1Max4000WithLang_Type[] otherInfoField;

        private CountryCode_Type[] resCountryCodeField;

        private CbcSummaryListElementsType_EnumType[] summaryRefField;

        /// <remarks/>
        public DocSpec_Type DocSpec {
            get {
                return this.docSpecField;
            }
            set {
                this.docSpecField = value;
            }
        }

        /// <remarks/>
        [XmlElement("OtherInfo")]
        public StringMin1Max4000WithLang_Type[] OtherInfo {
            get {
                return this.otherInfoField;
            }
            set {
                this.otherInfoField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ResCountryCode")]
        public CountryCode_Type[] ResCountryCode {
            get {
                return this.resCountryCodeField;
            }
            set {
                this.resCountryCodeField = value;
            }
        }

        /// <remarks/>
        [XmlElement("SummaryRef")]
        public CbcSummaryListElementsType_EnumType[] SummaryRef {
            get {
                return this.summaryRefField;
            }
            set {
                this.summaryRefField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbcstf:v5")]
    public partial class DocSpec_Type {

        private OECDDocTypeIndic_EnumType docTypeIndicField;

        private string docRefIdField;

        private string corrMessageRefIdField;

        private string corrDocRefIdField;

        /// <remarks/>
        public OECDDocTypeIndic_EnumType DocTypeIndic {
            get {
                return this.docTypeIndicField;
            }
            set {
                this.docTypeIndicField = value;
            }
        }

        /// <remarks/>
        public string DocRefId {
            get {
                return this.docRefIdField;
            }
            set {
                this.docRefIdField = value;
            }
        }

        /// <remarks/>
        public string CorrMessageRefId {
            get {
                return this.corrMessageRefIdField;
            }
            set {
                this.corrMessageRefIdField = value;
            }
        }

        /// <remarks/>
        public string CorrDocRefId {
            get {
                return this.corrDocRefIdField;
            }
            set {
                this.corrDocRefIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:cbcstf:v5")]
    public enum OECDDocTypeIndic_EnumType {

        /// <remarks/>
        OECD0,

        /// <remarks/>
        OECD1,

        /// <remarks/>
        OECD2,

        /// <remarks/>
        OECD3,

        /// <remarks/>
        OECD10,

        /// <remarks/>
        OECD11,

        /// <remarks/>
        OECD12,

        /// <remarks/>
        OECD13,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public enum CbcSummaryListElementsType_EnumType {

        /// <remarks/>
        CBC601,

        /// <remarks/>
        CBC602,

        /// <remarks/>
        CBC603,

        /// <remarks/>
        CBC604,

        /// <remarks/>
        CBC605,

        /// <remarks/>
        CBC606,

        /// <remarks/>
        CBC607,

        /// <remarks/>
        CBC608,

        /// <remarks/>
        CBC609,

        /// <remarks/>
        CBC610,

        /// <remarks/>
        CBC611,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class ConstituentEntity_Type {

        private OrganisationParty_Type constEntityField;

        private UltimateParentEntityRole_EnumType roleField;

        private bool roleFieldSpecified;

        private CountryCode_Type incorpCountryCodeField;

        private bool incorpCountryCodeFieldSpecified;

        private CbcBizActivityType_EnumType[] bizActivitiesField;

        private string otherEntityInfoField;

        /// <remarks/>
        public OrganisationParty_Type ConstEntity {
            get {
                return this.constEntityField;
            }
            set {
                this.constEntityField = value;
            }
        }

        /// <remarks/>
        public UltimateParentEntityRole_EnumType Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool RoleSpecified {
            get {
                return this.roleFieldSpecified;
            }
            set {
                this.roleFieldSpecified = value;
            }
        }

        /// <remarks/>
        public CountryCode_Type IncorpCountryCode {
            get {
                return this.incorpCountryCodeField;
            }
            set {
                this.incorpCountryCodeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool IncorpCountryCodeSpecified {
            get {
                return this.incorpCountryCodeFieldSpecified;
            }
            set {
                this.incorpCountryCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement("BizActivities")]
        public CbcBizActivityType_EnumType[] BizActivities {
            get {
                return this.bizActivitiesField;
            }
            set {
                this.bizActivitiesField = value;
            }
        }

        /// <remarks/>
        public string OtherEntityInfo {
            get {
                return this.otherEntityInfoField;
            }
            set {
                this.otherEntityInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class OrganisationParty_Type {

        private CountryCode_Type[] resCountryCodeField;

        private TIN_Type tINField;

        private OrganisationIN_Type[] inField;

        private NameOrganisation_Type[] nameField;

        private Address_Type[] addressField;

        /// <remarks/>
        [XmlElement("ResCountryCode")]
        public CountryCode_Type[] ResCountryCode {
            get {
                return this.resCountryCodeField;
            }
            set {
                this.resCountryCodeField = value;
            }
        }

        /// <remarks/>
        public TIN_Type TIN {
            get {
                return this.tINField;
            }
            set {
                this.tINField = value;
            }
        }

        /// <remarks/>
        [XmlElement("IN")]
        public OrganisationIN_Type[] IN {
            get {
                return this.inField;
            }
            set {
                this.inField = value;
            }
        }

        /// <remarks/>
        [XmlElement("Name")]
        public NameOrganisation_Type[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlElement("Address")]
        public Address_Type[] Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class TIN_Type {

        private CountryCode_Type issuedByField;

        private bool issuedByFieldSpecified;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public CountryCode_Type issuedBy {
            get {
                return this.issuedByField;
            }
            set {
                this.issuedByField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool issuedBySpecified {
            get {
                return this.issuedByFieldSpecified;
            }
            set {
                this.issuedByFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class OrganisationIN_Type {

        private CountryCode_Type issuedByField;

        private bool issuedByFieldSpecified;

        private string iNTypeField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public CountryCode_Type issuedBy {
            get {
                return this.issuedByField;
            }
            set {
                this.issuedByField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool issuedBySpecified {
            get {
                return this.issuedByFieldSpecified;
            }
            set {
                this.issuedByFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string INType {
            get {
                return this.iNTypeField;
            }
            set {
                this.iNTypeField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class NameOrganisation_Type {

        private string valueField;

        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class Address_Type {

        private CountryCode_Type countryCodeField;

        private object[] itemsField;

        private OECDLegalAddressType_EnumType legalAddressTypeField;

        private bool legalAddressTypeFieldSpecified;

        /// <remarks/>
        public CountryCode_Type CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        [XmlElement("AddressFix", typeof(AddressFix_Type))]
        [XmlElement("AddressFree", typeof(string))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public OECDLegalAddressType_EnumType legalAddressType {
            get {
                return this.legalAddressTypeField;
            }
            set {
                this.legalAddressTypeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool legalAddressTypeSpecified {
            get {
                return this.legalAddressTypeFieldSpecified;
            }
            set {
                this.legalAddressTypeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class AddressFix_Type {

        private string streetField;

        private string buildingIdentifierField;

        private string suiteIdentifierField;

        private string floorIdentifierField;

        private string districtNameField;

        private string pOBField;

        private string postCodeField;

        private string cityField;

        private string countrySubentityField;

        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }

        /// <remarks/>
        public string BuildingIdentifier {
            get {
                return this.buildingIdentifierField;
            }
            set {
                this.buildingIdentifierField = value;
            }
        }

        /// <remarks/>
        public string SuiteIdentifier {
            get {
                return this.suiteIdentifierField;
            }
            set {
                this.suiteIdentifierField = value;
            }
        }

        /// <remarks/>
        public string FloorIdentifier {
            get {
                return this.floorIdentifierField;
            }
            set {
                this.floorIdentifierField = value;
            }
        }

        /// <remarks/>
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }

        /// <remarks/>
        public string POB {
            get {
                return this.pOBField;
            }
            set {
                this.pOBField = value;
            }
        }

        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }

        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string CountrySubentity {
            get {
                return this.countrySubentityField;
            }
            set {
                this.countrySubentityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:cbcstf:v5")]
    public enum OECDLegalAddressType_EnumType {

        /// <remarks/>
        OECD301,

        /// <remarks/>
        OECD302,

        /// <remarks/>
        OECD303,

        /// <remarks/>
        OECD304,

        /// <remarks/>
        OECD305,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public enum UltimateParentEntityRole_EnumType {

        /// <remarks/>
        CBC801,

        /// <remarks/>
        CBC802,

        /// <remarks/>
        CBC803,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public enum CbcBizActivityType_EnumType {

        /// <remarks/>
        CBC501,

        /// <remarks/>
        CBC502,

        /// <remarks/>
        CBC503,

        /// <remarks/>
        CBC504,

        /// <remarks/>
        CBC505,

        /// <remarks/>
        CBC506,

        /// <remarks/>
        CBC507,

        /// <remarks/>
        CBC508,

        /// <remarks/>
        CBC509,

        /// <remarks/>
        CBC510,

        /// <remarks/>
        CBC511,

        /// <remarks/>
        CBC512,

        /// <remarks/>
        CBC513,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class MonAmnt_Type {

        private currCode_Type currCodeField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public currCode_Type currCode {
            get {
                return this.currCodeField;
            }
            set {
                this.currCodeField = value;
            }
        }

        /// <remarks/>
        [XmlText(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:isocbctypes:v1")]
    public enum currCode_Type {

        /// <remarks/>
        AED,

        /// <remarks/>
        AFN,

        /// <remarks/>
        ALL,

        /// <remarks/>
        AMD,

        /// <remarks/>
        ANG,

        /// <remarks/>
        AOA,

        /// <remarks/>
        ARS,

        /// <remarks/>
        AUD,

        /// <remarks/>
        AWG,

        /// <remarks/>
        AZN,

        /// <remarks/>
        BAM,

        /// <remarks/>
        BBD,

        /// <remarks/>
        BDT,

        /// <remarks/>
        BGN,

        /// <remarks/>
        BHD,

        /// <remarks/>
        BIF,

        /// <remarks/>
        BMD,

        /// <remarks/>
        BND,

        /// <remarks/>
        BOB,

        /// <remarks/>
        BOV,

        /// <remarks/>
        BRL,

        /// <remarks/>
        BSD,

        /// <remarks/>
        BTN,

        /// <remarks/>
        BWP,

        /// <remarks/>
        BYN,

        /// <remarks/>
        BYR,

        /// <remarks/>
        BZD,

        /// <remarks/>
        CAD,

        /// <remarks/>
        CDF,

        /// <remarks/>
        CHE,

        /// <remarks/>
        CHF,

        /// <remarks/>
        CHW,

        /// <remarks/>
        CLF,

        /// <remarks/>
        CLP,

        /// <remarks/>
        CNY,

        /// <remarks/>
        COP,

        /// <remarks/>
        COU,

        /// <remarks/>
        CRC,

        /// <remarks/>
        CUC,

        /// <remarks/>
        CUP,

        /// <remarks/>
        CVE,

        /// <remarks/>
        CZK,

        /// <remarks/>
        DJF,

        /// <remarks/>
        DKK,

        /// <remarks/>
        DOP,

        /// <remarks/>
        DZD,

        /// <remarks/>
        EGP,

        /// <remarks/>
        ERN,

        /// <remarks/>
        ETB,

        /// <remarks/>
        EUR,

        /// <remarks/>
        FJD,

        /// <remarks/>
        FKP,

        /// <remarks/>
        GBP,

        /// <remarks/>
        GEL,

        /// <remarks/>
        GHS,

        /// <remarks/>
        GIP,

        /// <remarks/>
        GMD,

        /// <remarks/>
        GNF,

        /// <remarks/>
        GTQ,

        /// <remarks/>
        GYD,

        /// <remarks/>
        HKD,

        /// <remarks/>
        HNL,

        /// <remarks/>
        HRK,

        /// <remarks/>
        HTG,

        /// <remarks/>
        HUF,

        /// <remarks/>
        IDR,

        /// <remarks/>
        ILS,

        /// <remarks/>
        INR,

        /// <remarks/>
        IQD,

        /// <remarks/>
        IRR,

        /// <remarks/>
        ISK,

        /// <remarks/>
        JMD,

        /// <remarks/>
        JOD,

        /// <remarks/>
        JPY,

        /// <remarks/>
        KES,

        /// <remarks/>
        KGS,

        /// <remarks/>
        KHR,

        /// <remarks/>
        KMF,

        /// <remarks/>
        KPW,

        /// <remarks/>
        KRW,

        /// <remarks/>
        KWD,

        /// <remarks/>
        KYD,

        /// <remarks/>
        KZT,

        /// <remarks/>
        LAK,

        /// <remarks/>
        LBP,

        /// <remarks/>
        LKR,

        /// <remarks/>
        LRD,

        /// <remarks/>
        LSL,

        /// <remarks/>
        LTL,

        /// <remarks/>
        LVL,

        /// <remarks/>
        LYD,

        /// <remarks/>
        MAD,

        /// <remarks/>
        MDL,

        /// <remarks/>
        MGA,

        /// <remarks/>
        MKD,

        /// <remarks/>
        MMK,

        /// <remarks/>
        MNT,

        /// <remarks/>
        MOP,

        /// <remarks/>
        MRO,

        /// <remarks/>
        MRU,

        /// <remarks/>
        MUR,

        /// <remarks/>
        MVR,

        /// <remarks/>
        MWK,

        /// <remarks/>
        MXN,

        /// <remarks/>
        MXV,

        /// <remarks/>
        MYR,

        /// <remarks/>
        MZN,

        /// <remarks/>
        NAD,

        /// <remarks/>
        NGN,

        /// <remarks/>
        NIO,

        /// <remarks/>
        NOK,

        /// <remarks/>
        NPR,

        /// <remarks/>
        NZD,

        /// <remarks/>
        OMR,

        /// <remarks/>
        PAB,

        /// <remarks/>
        PEN,

        /// <remarks/>
        PGK,

        /// <remarks/>
        PHP,

        /// <remarks/>
        PKR,

        /// <remarks/>
        PLN,

        /// <remarks/>
        PYG,

        /// <remarks/>
        QAR,

        /// <remarks/>
        RON,

        /// <remarks/>
        RSD,

        /// <remarks/>
        RUB,

        /// <remarks/>
        RWF,

        /// <remarks/>
        SAR,

        /// <remarks/>
        SBD,

        /// <remarks/>
        SCR,

        /// <remarks/>
        SDG,

        /// <remarks/>
        SEK,

        /// <remarks/>
        SGD,

        /// <remarks/>
        SHP,

        /// <remarks/>
        SLL,

        /// <remarks/>
        SOS,

        /// <remarks/>
        SRD,

        /// <remarks/>
        SSP,

        /// <remarks/>
        STD,

        /// <remarks/>
        STN,

        /// <remarks/>
        SVC,

        /// <remarks/>
        SYP,

        /// <remarks/>
        SZL,

        /// <remarks/>
        THB,

        /// <remarks/>
        TJS,

        /// <remarks/>
        TMT,

        /// <remarks/>
        TND,

        /// <remarks/>
        TOP,

        /// <remarks/>
        TRY,

        /// <remarks/>
        TTD,

        /// <remarks/>
        TWD,

        /// <remarks/>
        TZS,

        /// <remarks/>
        UAH,

        /// <remarks/>
        UGX,

        /// <remarks/>
        USD,

        /// <remarks/>
        USN,

        /// <remarks/>
        USS,

        /// <remarks/>
        UYI,

        /// <remarks/>
        UYU,

        /// <remarks/>
        UYW,

        /// <remarks/>
        UZS,

        /// <remarks/>
        VEF,

        /// <remarks/>
        VES,

        /// <remarks/>
        VND,

        /// <remarks/>
        VUV,

        /// <remarks/>
        WST,

        /// <remarks/>
        XAF,

        /// <remarks/>
        XAG,

        /// <remarks/>
        XAU,

        /// <remarks/>
        XBA,

        /// <remarks/>
        XBB,

        /// <remarks/>
        XBC,

        /// <remarks/>
        XBD,

        /// <remarks/>
        XCD,

        /// <remarks/>
        XDR,

        /// <remarks/>
        XFU,

        /// <remarks/>
        XOF,

        /// <remarks/>
        XPD,

        /// <remarks/>
        XPF,

        /// <remarks/>
        XPT,

        /// <remarks/>
        XSU,

        /// <remarks/>
        XUA,

        /// <remarks/>
        XXX,

        /// <remarks/>
        YER,

        /// <remarks/>
        ZAR,

        /// <remarks/>
        ZMW,

        /// <remarks/>
        ZWL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class CorrectableCbcReport_Type {

        private DocSpec_Type docSpecField;

        private CountryCode_Type resCountryCodeField;

        private CorrectableCbcReport_TypeSummary summaryField;

        private ConstituentEntity_Type[] constEntitiesField;

        /// <remarks/>
        public DocSpec_Type DocSpec {
            get {
                return this.docSpecField;
            }
            set {
                this.docSpecField = value;
            }
        }

        /// <remarks/>
        public CountryCode_Type ResCountryCode {
            get {
                return this.resCountryCodeField;
            }
            set {
                this.resCountryCodeField = value;
            }
        }

        /// <remarks/>
        public CorrectableCbcReport_TypeSummary Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ConstEntities")]
        public ConstituentEntity_Type[] ConstEntities {
            get {
                return this.constEntitiesField;
            }
            set {
                this.constEntitiesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oecd:ties:cbc:v2")]
    public partial class CorrectableCbcReport_TypeSummary {

        private CorrectableCbcReport_TypeSummaryRevenues revenuesField;

        private MonAmnt_Type profitOrLossField;

        private MonAmnt_Type taxPaidField;

        private MonAmnt_Type taxAccruedField;

        private MonAmnt_Type capitalField;

        private MonAmnt_Type earningsField;

        private string nbEmployeesField;

        private MonAmnt_Type assetsField;

        /// <remarks/>
        public CorrectableCbcReport_TypeSummaryRevenues Revenues {
            get {
                return this.revenuesField;
            }
            set {
                this.revenuesField = value;
            }
        }

        /// <remarks/>
        public MonAmnt_Type ProfitOrLoss {
            get {
                return this.profitOrLossField;
            }
            set {
                this.profitOrLossField = value;
            }
        }

        /// <remarks/>
        public MonAmnt_Type TaxPaid {
            get {
                return this.taxPaidField;
            }
            set {
                this.taxPaidField = value;
            }
        }

        /// <remarks/>
        public MonAmnt_Type TaxAccrued {
            get {
                return this.taxAccruedField;
            }
            set {
                this.taxAccruedField = value;
            }
        }

        /// <remarks/>
        public MonAmnt_Type Capital {
            get {
                return this.capitalField;
            }
            set {
                this.capitalField = value;
            }
        }

        /// <remarks/>
        public MonAmnt_Type Earnings {
            get {
                return this.earningsField;
            }
            set {
                this.earningsField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string NbEmployees {
            get {
                return this.nbEmployeesField;
            }
            set {
                this.nbEmployeesField = value;
            }
        }

        /// <remarks/>
        public MonAmnt_Type Assets {
            get {
                return this.assetsField;
            }
            set {
                this.assetsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oecd:ties:cbc:v2")]
    public partial class CorrectableCbcReport_TypeSummaryRevenues {

        private MonAmnt_Type unrelatedField;

        private MonAmnt_Type relatedField;

        private MonAmnt_Type totalField;

        /// <remarks/>
        public MonAmnt_Type Unrelated {
            get {
                return this.unrelatedField;
            }
            set {
                this.unrelatedField = value;
            }
        }

        /// <remarks/>
        public MonAmnt_Type Related {
            get {
                return this.relatedField;
            }
            set {
                this.relatedField = value;
            }
        }

        /// <remarks/>
        public MonAmnt_Type Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(CorrectableReportingEntity_Type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class ReportingEntity_Type {

        private OrganisationParty_Type entityField;

        private string nameMNEGroupField;

        private CbcReportingRole_EnumType reportingRoleField;

        private ReportingEntity_TypeReportingPeriod reportingPeriodField;

        /// <remarks/>
        public OrganisationParty_Type Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }

        /// <remarks/>
        public string NameMNEGroup {
            get {
                return this.nameMNEGroupField;
            }
            set {
                this.nameMNEGroupField = value;
            }
        }

        /// <remarks/>
        public CbcReportingRole_EnumType ReportingRole {
            get {
                return this.reportingRoleField;
            }
            set {
                this.reportingRoleField = value;
            }
        }

        /// <remarks/>
        public ReportingEntity_TypeReportingPeriod ReportingPeriod {
            get {
                return this.reportingPeriodField;
            }
            set {
                this.reportingPeriodField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public enum CbcReportingRole_EnumType {

        /// <remarks/>
        CBC701,

        /// <remarks/>
        CBC702,

        /// <remarks/>
        CBC703,

        /// <remarks/>
        CBC704,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="urn:oecd:ties:cbc:v2")]
    public partial class ReportingEntity_TypeReportingPeriod {

        private System.DateTime startDateField;

        private System.DateTime endDateField;

        /// <remarks/>
        [XmlElement(DataType="date")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType="date")]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class CorrectableReportingEntity_Type : ReportingEntity_Type {

        private DocSpec_Type docSpecField;

        /// <remarks/>
        public DocSpec_Type DocSpec {
            get {
                return this.docSpecField;
            }
            set {
                this.docSpecField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="urn:oecd:ties:cbc:v2")]
    public partial class CbcBody_Type {

        private CorrectableReportingEntity_Type reportingEntityField;

        private CorrectableCbcReport_Type[] cbcReportsField;

        private CorrectableAdditionalInfo_Type[] additionalInfoField;

        /// <remarks/>
        public CorrectableReportingEntity_Type ReportingEntity {
            get {
                return this.reportingEntityField;
            }
            set {
                this.reportingEntityField = value;
            }
        }

        /// <remarks/>
        [XmlElement("CbcReports")]
        public CorrectableCbcReport_Type[] CbcReports {
            get {
                return this.cbcReportsField;
            }
            set {
                this.cbcReportsField = value;
            }
        }

        /// <remarks/>
        [XmlElement("AdditionalInfo")]
        public CorrectableAdditionalInfo_Type[] AdditionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
            }
        }
    }
}